export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="sunaku"

COMPLETION_WAITING_DOTS="true"

plugins=(
  git,
  pyenv,
  vi-mode,
  last-working-dir,
  docker
)

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

alias vi=vim

# golang
export PATH=$PATH:$HOME/go/bin
